import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */
const sidebars: SidebarsConfig = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  docToolSidebar: [{type: 'autogenerated', dirName: 'docTools'}],
  teamWorkSidebar: [{type: 'autogenerated', dirName: 'teamWork'}],
  venvSidebar: [{type: 'autogenerated', dirName: 'venv'}],
  cSidebar: [{type: 'autogenerated', dirName: 'c'}],
  cppSidebar: [{type: 'autogenerated', dirName: 'cpp'}],
  pythonSidebar: [{type: 'autogenerated', dirName: 'python'}],
  stmSidebar: [{type: 'autogenerated', dirName: 'stm'}],
  espSidebar: [{type: 'autogenerated', dirName: 'esp'}],
  ros1Sidebar: [{type: 'autogenerated', dirName: 'ros1'}],
  ros2Sidebar: [{type: 'autogenerated', dirName: 'ros2'}],
  // But you can create a sidebar manually
  /*
  tutorialSidebar: [
    'intro',
    'hello',
    {
      type: 'category',
      label: 'Tutorial',
      items: ['tutorial-basics/create-a-document'],
    },
  ],
   */
};

export default sidebars;
